### ISSUE TITLE
Implicit declaration of function 'EVP_cleanup' is invalid in C99

### ISSUE THREAD

**Issue by adm1n007** [rmaddy/VerifyStoreReceiptiOS#18]
build with xcode Version 11.7 (11E801a)
