### ISSUE TITLE
Implicit declaration of function 'OpenSSL_add_all_digests' is invalid in C99

### ISSUE THREAD

**Issue by adm1n007** [rmaddy/VerifyStoreReceiptiOS#17]
build with xcode Version 11.7 (11E801a)
